export const CHANGE_CATEGORIES = "songs/CHANGE_CATEGORIES";
export const CHANGE_CATEGOTY_SONGS = "songs/CHANGE_CATEGOTY_SONGS";

export const CHANGE_CURRENT_CATEGORY = "songs/CHANGE_CURRENT_CATEGORY";